# .travis.yml

language: php

# Setup a global environemnt and overide as needed
env:
  global:
    - WP_TRAVISCI=phpunit

branches:
  only:
  - master

# Next we define our matrix of additional build configurations to test against.
matrix:
  include:
  - php: "5.2"
    dist: precise
    env: WP_VERSION=latest
  - php: "5.3"
    dist: precise
    env: WP_VERSION=latest
  - php: "5.5"
    env: WP_VERSION=latest
  - php: "5.6"
    env: WP_VERSION=latest
  - php: "5.6"
    env: WP_VERSION=master
  - php: "5.6"
    env: WP_VERSION=previous
  - php: "7.0"
    env: WP_VERSION=latest
  - php: "7.1"
    env: WP_VERSION=latest
  - php: "7.2"
    env: WP_VERSION=latest
    
sudo: false
